import time

def handle_event(event):
    """
    Handles security events generated by ML system
    event = {
        'type': str,
        'severity': str,
        'message': str
    }
    """

    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")

    print("\n================ ALERT ================")
    print(f"TIME     : {timestamp}")
    print(f"TYPE     : {event['type']}")
    print(f"SEVERITY : {event['severity']}")
    print(f"MESSAGE  : {event['message']}")
    print("======================================\n")

    # ---- ACTIONS BASED ON SEVERITY ----
    if event["severity"] == "CRITICAL":
        trigger_police_alert(event)

    elif event["severity"] == "HIGH":
        notify_bank_security(event)

    elif event["severity"] == "MEDIUM":
        log_event(event)


def trigger_police_alert(event):
    print("🚨 POLICE ALERT SENT 🚓")


def notify_bank_security(event):
    print("⚠️ BANK SECURITY NOTIFIED")


def log_event(event):
    print("ℹ️ EVENT LOGGED")